/**
 * Curated icon set. Import icons from here rather than lucide-react directly
 * so the app keeps a consistent, deliberate vocabulary of icons.
 */
export {
  AlertTriangle,
  ArrowRight,
  Calendar,
  CalendarDays,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  Circle,
  Clock,
  Copy,
  Download,
  FileText,
  Filter,
  Grid2x2,
  Import,
  Inbox,
  LayoutDashboard,
  Link2,
  ListTodo,
  Loader2,
  Menu as MenuIcon,
  MoreHorizontal,
  Paperclip,
  Pencil,
  Plus,
  Search,
  Settings,
  Sparkles,
  StickyNote,
  Trash2,
  Upload,
  Wrench,
  X,
} from 'lucide-react';
