ALTER TABLE notes
    ADD COLUMN display_order INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN position_x INTEGER,
    ADD COLUMN position_y INTEGER,
    ADD COLUMN width INTEGER,
    ADD COLUMN height INTEGER,
    ADD COLUMN color VARCHAR(40),
    ADD COLUMN z_index INTEGER NOT NULL DEFAULT 0;
